apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchen-api
  template:
    metadata:
      labels:
        app: kitchen-api
    spec:
      containers:
        - name: kitchen-api
          image: fabianogoes/kitchen-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 1m
          envFrom:
            - secretRef:
                name: kitchen-secret
          env:
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: kitchen-secret
                  key: DB_URI
            - name: DB_NAME
              value: "tech_challenge_kitchen_db"
            - name: APP_NAME
              value: kitchen-api
            - name: APP_ENV
              value: "production"
            - name: APP_PORT
              value: ":8080"
            - name: API_VERSION
              value: "4.0"
      restartPolicy: Always

